#!/bin/bash
echo ""
echo "########################################"
echo "# Docker Hub - Drupal 9 Start  #";
echo "########################################"
echo ""
echo "[1/3]-> Starting Docker containers."
docker stop $(docker ps -aq) 
docker-compose down --remove-orphans
docker-compose up --build -d db web phpmyadmin

# Restart all
docker-compose down --remove-orphans
docker-compose up --build -d db web phpmyadmin

echo "[2/3]-> Setting up MYSQL configurations."

echo "RUNNING: docker exec -i drupal_db /usr/bin/mysql -uroot -proot -e \"SET GLOBAL max_allowed_packet=134217728;\""
docker exec -i drupal_db /usr/bin/mysql -uroot -proot -e "SET GLOBAL max_allowed_packet=134217728;"

echo "[3/3]-> Checking PHP dependencies."
echo "RUNNING: docker exec -it drupal_web composer install"
docker exec -it drupal_web composer install

echo ""
echo "##########################################"
echo "# Docker Hub - Drupal 9 Started  #";
echo "##########################################"
echo ""
